#!/bin/bash

pngquant --strip --speed 1 --force --output docs/maze.png docs/maze.png
pngquant --strip --speed 1 --force --output docs/zombie.png docs/zombie.png
pngquant --strip --speed 1 --force --output docs/sonic.png docs/sonic.png
